#!/usr/bin/bash -x
umask 2
CWSNAME=$1
BUILDER=$2
BUILDNO=$3
cd ..
echo "Building..."
. ./solar.env

# hack ause
export WITH_LANG="en-US de"

cd $SRC_ROOT/instsetoo_native
$PERL $SOLARENV/bin/build.pl --all -P4 -- -P2
RETVAL=$?
if [ $? -eq 0 ]; then
  $PERL $SOLARENV/bin/deliver.pl
  RETVAL=$?
  if [ $? -eq 0 ]; then
    cd $SRC_ROOT/instset_native
    $PERL $SOLARENV/bin/build.pl --all -P4 -- -P2
    RETVAL=$?
    if [ $? -eq 0 ]; then
      $PERL $SOLARENV/bin/deliver.pl
      RETVAL=$?
    fi
  fi
fi

# Sending mail to CWS owner
USERNAME=$(cws query owner | tail -1)
MACHINE=$(uname -a)
echo "Subject: StarOffice Buildbot: build of $CWSNAME finished" > mail.tmp
echo "$MACHINE ($BUILDER) has finished build of your CWS $CWSNAME with exit code $RETVAL (0: good, 1: bad)" >> mail.tmp
echo "" >> mail.tmp
echo "Visit http://so-berlin:8080/builders/$BUILDER/builds/$BUILDNO for output logs." >> mail.tmp
echo "" >> mail.tmp
echo "If you discover any problems with the Buildbot machines contact Team Tools & RelEng." >> mail.tmp
echo "" >> mail.tmp
echo "Thank you for using our StarOffice Buildbots :-)" >> mail.tmp

mail $USERNAME < mail.tmp

exit $RETVAL
