#!/usr/bin/bash -x
echo "Setting solar environment..."

export PATH=$PATH:/so/env/etools
export VCSID=christianlins
export ENV_ROOT=/so/env
export OSTYPE=solaris

SOLARFILE=./solar.env
PLATFORM=$(basename $(pwd))

# define setsolar
function setsolar
{
    perl $ENV_ROOT/etools/setsolar.pl -file $SOLARFILE -shell bash "$@"
    . $SOLARFILE
}

function setcws
{
    #perl $ENV_ROOT/etools/setcws.pl /buildbot/solar.env "$@"
    perl $ENV_ROOT/etools/setcws.pl $SOLARFILE "$@" -- -shell bash
    . $SOLARFILE
}

# Determine milestone of given CWS
export SOURCE_ROOT=/cws/so-cwsserv02/$1

# Create output dir and ignore result if existing
mkdir -p $SOURCE_ROOT/DEV300/$PLATFORM

# Check if a pro build is forced
echo $(pwd) | egrep .pro\$ > /dev/null

# Set environment to CWS
if [ $? -eq 0 ]; then
echo "Product build"
setcws $1 $2 -pro
else
echo "Non-Product build"
setcws $1 $2
fi

if [ "$CWS_WORK_STAMP" = "$1" ]; then
  exit 0
else
  exit 1
fi
