#!/usr/bin/bash -x
. ./solar.env
PATH=$PATH:/usr/X/bin
Xvfb :2 &
PID=$!

export DISPLAY=:2
export EXTERNAL_WARNINGS_NOT_ERRORS="TRUE"

cd $SRC_ROOT/smoketestoo_native
$PERL $SOLARENV/bin/build.pl
RETVAL=$?

# Stop Xvfb
kill -15 $PID

exit $RETVAL
