#!/usr/bin/env perl
#
# This is a hack to run SLOCCOUNT and send the data back.
# it is not a finished product
#

use warnings;
use strict;

use XML::Simple;
use LWP::UserAgent;
use LWP::Simple;
use HTTP::Request::Common;
use Getopt::Long;


# pinched form cwsget
sub latest_milestone($)
{
    my $master= shift;
    my $url = 'http://go-oo.org/tinderbox/tags/tag-latest-master-list';
    
    my $response = get($url) || die "Couldn't get $url\n";
    foreach(split /\n/, $response)
    {
	unless (/\#.*/)
	{
	    (my $name, my $base, my $tag, my $dirs) = split / : /, $_;
	    return $name if $name =~ /$master/;
	}
    }
    die "couldn't find latest milestone!\n";
}


my $server_url= "http://termite.go-oo.org:3000";


my $branch= '';
my $buildername;
my $slavename;
my $buildnumber;
my $help_option;
GetOptions('help'        => \$help_option,
	   'branch:s'    => \$branch,
	   'buildernamer:s' => \$buildername,
	   'slavename:s'    => \$slavename,
	   'buildnumber:s'  => \$buildnumber);
if ($help_option)
{
    print STDERR "This script is undocumented.  It is meant to be invoked by buildbot, and should not be run by the user\n";
    exit 1;
}

if ($branch eq '')
{
    $branch= latest_milestone('SRC680');
}

# discern cws,pws here
my $cws, my $pws;
my @thingy= split /_/, $branch; # coulnd't think of a better name
if (@thingy == 3)
{ # cws: 'cws_src680_dmake411'
    $pws= uc $thingy[1];
    $cws= $thingy[2];
}
elsif (@thingy == 2)
{ # milestone: 'SRC680_m225'
    $pws= $thingy[0];
    $cws = $thingy[1];
}
else
{
    die "$branch doesn't seem to be cws or milestone!\n";
}

# run sloccount
my $sloc_output= `sloccount *`;
die "couldn't run sloccount!\n" unless $? == 0;

# parse output
my $sloc;
foreach my $line (split /\n/, $sloc_output)
{
    if ($line=~/Total Physical Source Lines of Code \(SLOC\)\s+=\s+([\d,]+)/)
    {
	$sloc= $1;
	$sloc=~ s/,//g; # there must be a more elegant way
    }
}

my $hashref= 
{
    'build' => {
	'pws' => $pws,
	'cws' => $cws,
	'builder' => $buildername,
	'host' => $slavename,
	'build_number' => $buildnumber,
	},
	    'data_item' =>
	{
	    'data_type' => 'sloccount',
	    'data' => {
		'SLOC' => $sloc
		}
	}
};

my $xml= XMLout($hashref, NoAttr => 1, RootName => 'data');
 
my $ua = LWP::UserAgent->new;
$ua->timeout(10);
$ua->env_proxy;
 
my $response = $ua->request(POST "$server_url/data.xml",
			    Content_Type => 'text/xml',
			    Content => $xml);
if ($response->is_success) 
{
    print $response->status_line; # b0rked    
}
else 
{
    die $response->content;  # worked!
}
