#!/bin/bash

#if [ "$1" == "debug" ]
#then
#  set -x
#fi

scripts=../..
checkout=slave

mkdir script_checkout
cd script_checkout || exit 1
svn co http://ootermite.googlecode.com/svn/trunk/buildbot/slave || exit 1
cd $checkout || exit 1

for file in cws_fetch svn-clean configure buildprep bootstrap ccsetup.sh compile Xvfb_stop.sh getOOoEnv smoketestoo bundle
do
  ok=
  err=

  if [ -f ../$scripts/$file ]
  then
    mv $file $file.co
    cp ../$scripts/$file $file
    if [ "`svn diff $file`" ]
    then
      echo
      echo File $file not up to date. Trying update.
      for rev in `svn log $file |grep "^r[0-9]* | "| head -n 5 | sed -e "s/r//" -e "s/ .*//"`
      do
        if [ -z "$ok" ]
        then
          echo checking against revision $rev of $file
          if [ -z "`svn diff -r $rev $file || echo error`" ]
          then
            echo revision matches, copying new file
            if [ "$1" == "debug" ]
            then 
              diff -u $file.co ../$scripts/$file
            else
              cp ../$scripts/$file ../$scripts/$file.bak || err="err"
              [ "$err" ] || cp $file.co ../$scripts/$file || err="err"
            fi
            ok=ok
          fi
        fi
      done
    fi
  else
    echo
    echo file $file does not exist. installing
    cp $file ../$scripts/$file || err="err"
    ok=ok
  fi
  if [ -z "$ok" ]
  then
    echo warning: could not update file $file. Seems to be modified locally
  fi
  if [ "$err" ]
  then
    echo warning: could not update file $file. Problem accessing file
    warn=2
  fi

done

#copy new worker. will be renamed by maintenance script
cp maintenance_worker ../$scripts/maintenance_worker_new

cd ../.. || exit 1

rm -rf script_checkout

echo $warn

exit $warn

#diff -u ../bootstrap slave || return=65
#diff -u ../buildprep slave || return=65
#diff -u ../bundle slave || return=65
#diff -u ../ccsetup.sh slave || return=65
#diff -u ../compile slave || return=65
#diff -u ../configure slave || return=65
diff -u ../cws_fetch slave || return=65
#diff -u ../getOOoEnv slave || return=65
#diff -u ../smoketestoo slave || return=65
#diff -u ../svn-clean slave || return=65
#diff -u ../Xvfb_stop.sh slave || return=65

cd ..

rm -rf script_checkout

exit $return

bundle.soli
bundle.sols
bundle.win
cws_fetch.cfg
maintenance
maintenance_worker
README
sloccount
steps.config.sample
