#!/bin/bash -x

cd ../..
mkdir script_checkout
cd script_checkout || exit 1
svn co http://ootermite.googlecode.com/svn/trunk/buildbot/slave

ls -l

diff -u slave/bootstrap .. || return=65
diff -u slave/buildprep .. || return=65
diff -u slave/bundle .. || return=65
diff -u slave/compile .. || return=65
diff -u slave/configure .. || return=65
diff -u slave/cws_fetch .. || return=65
diff -u slave/smoketestoo .. || return=65

cd ..

rm -rf script_checkout

exit $return

bundle.soli
bundle.sols
bundle.win
ccsetup.sh
cws_fetch.cfg
maintenance
maintenance_worker
README
sloccount
steps.config.sample
svn-clean
Xvfb_stop.sh
