#!/bin/bash -x

# read config
. ../../steps.config

# for those requiring X
if [ -f LinuxX86Env.Set.sh -o -f LinuxX86-64Env.Set.sh -o -f LinuxIntelEnv.Set.sh -o -f SolarisX86Env.Set.sh -o -f SolarisSparcEnv.Set.sh ]
then
    if [ -z $XvfbBinary ]
    then
      XvfbBinary=/usr/bin/Xvfb
    fi
    $XvfbBinary :2 &
    export DISPLAY=:2
    export EXTERNAL_WARNINGS_NOT_ERRORS="TRUE"
    XStarted=Yes
fi

# for solaris X11 deadlock problem
if [ -f SolarisX86Env.Set.sh -o -f SolarisSparcEnv.Set.sh ]
then
    export SAL_NO_XINITTHREADS=TRUE
fi

# put name of OOo config file created by configure in $envname
. ../../getOOoEnv
. $envname

# hack to survive build.pl "feature" :(
export TMP=/tmp

export TEMP="/tmp"
if [ -d test ]
then
    workdir=`pwd`
    cd test && perl ../solenv/bin/build.pl && perl ../solenv/bin/deliver.pl
    cd $workdir
fi
cd smoketestoo_native && perl ../solenv/bin/build.pl
rcode=$?

[ "$XStarted" ] && ../../../Xvfb_stop.sh

exit $rcode

